#!/usr/bin/env ruby

require 'rake'
require 'pry-byebug'


abort "Usage: hack-vm <filename>" unless ARGV[0]

filename = ARGV[0].to_s
output = ARGV[1] || filename.ext(".asm")

abort "File not found at #{filename}" unless File.exists? filename

COMMAND_TYPES = %i[arithmetic push pop label goto if function return call]
ARITHMETIC =  %w[add sub neg eq gl lt and or not]

def command_for_line line
  cmd = line.split(' ').first

  return cmd.to_sym if COMMAND_TYPES.include? cmd.to_sym
  return :arithmetic if ARITHMETIC.include? cmd

  raise "Unknown command #{cmd}!"
end


def parse filename

  lines = File.open(filename).read.lines.to_a
  #remove comments and leading / trailing whitespace
  lines.map! {|l| l.strip }
  lines.delete_if {|l| l.start_with?('//') or l.empty?}

  #map each line to command and args
  lines.map do |l|
    cmd_type = command_for_line l

    cmd, arg1, arg2 = l.scan(/(\w+)\s?(\w+)?\s?(\w+)?/).flatten
    {cmd: cmd, cmd_type: cmd_type, arg1: arg1, arg2:arg2}
  end
end

class Writer

  def initialize
    @labelcount=0
    @lines=[]
  end

  def current_filename fname
    @fname = fname
  end


  def write_cmd cmd
    case cmd[:cmd_type]
    when :push, :pop
      write_push_pop cmd
    when :arithmetic
      write_arithmetic cmd
    else
      raise "unknown command #{cmd}"
    end
  end

  def finish name
    @lines << "\n"
    File.open(name,'w') { |f| f << @lines.join("\n")}
  end

  private 

  def label_id
    @labelcount+=1
    "#{@fname}.#{@labelcount}"
  end

  def write_arithmetic cmd
    pop "R13"

    #shortcut for one argument commands
    if cmd[:cmd] == "not"
      @lines.concat %W(@R13 D=!M @R15 M=D)
      push "R15"
      return
    end
    if cmd[:cmd] == "neg"
      @lines.concat %W(@R13 D=-M @R15 M=D)
      push "R15"
      return
    end

    #two argument commands
    pop "R14"

    #load r13 and r14 into d and m registers
    @lines.concat %W(@R13 D=M @R14)

    case cmd[:cmd]
    when "add"
      @lines.concat %W(D=D+M @R15 M=D)
    when "sub"
      @lines.concat %W(D=D-M @R15 M=D)
    when "and"
      @lines.concat %W(D=D&M @R15 M=D)
    when "or"
      @lines.concat %W(D=D|M @R15 M=D)
    when "eq","gt","lt"
      true_lbl = label_id
      end_lbl = label_id

      @lines.concat [
        "D=D-M",
        "@#{true_lbl}",
        "D;J#{cmd[:cmd].upcase}",
        "@0", #result is false
        "D=A",
        "@R15",
        "M=D",
        "@#{end_lbl}",
        "0;JMP",
        "(#{true_lbl})",
        "@-1",#result is true
        "D=A",
        "@R15",
        "M=D",
        "(#{end_lbl})"
      ]
    else
      raise "unsupported cmd #{cmd}"
    end

    push "R15"
  end

  def write_push_pop cmd
    case cmd[:cmd_type]
    when :push
      raise "unsupported segment! - #{cmd[:arg1]}" unless cmd[:arg1] == 'constant'

      @lines.concat %W(@#{cmd[:arg2]} D=A @R13 M=D)
      push "R13"
    when :pop
      raise "no pop commands supported!"
    else
      raise "invalid push pop command - #{cmd}"
    end
  end

  def push src
    @lines.concat %W(@#{src} D=M @SP A=M M=D)
    inc_sp
  end

  def pop dest
    dec_sp
    @lines.concat %W(A=M D=M @#{dest} M=D)
  end

  def inc_sp
    @lines.concat %W(@SP D=M M=D+1)
  end

  def dec_sp
    @lines.concat %W(@SP D=M M=D-1)
  end
end

writer = Writer.new
cmds = parse filename
writer.current_filename filename

cmds.each {|c| writer.write_cmd c }

writer.finish output

